# Generated by Django 4.1.4 on 2023-02-21 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthBuddy', '0002_foodmenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('month', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=5)),
                ('weight', models.FloatField(default=0)),
                ('fruits', models.FloatField(default=0)),
                ('vegs', models.FloatField(default=0)),
                ('meat', models.FloatField(default=0)),
                ('dairy', models.FloatField(default=0)),
                ('grain', models.FloatField(default=0)),
                ('others', models.FloatField(default=0)),
                ('notes', models.CharField(max_length=200)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
